language: node_js

node_js:
    - "4.2"
    - "5.6"

install:
    npm install

notification:
    email: 
        recipients:
            - vanpipy@gmail.com
        on_success: never
        on_failure: always

